### ISSUE TITLE
readme screenshots

### ISSUE THREAD

**Issue by logsol** [logsol/JuceLibPd#1]
![screen shot 2015-06-28 at 15 56 22](https://cloud.githubusercontent.com/assets/692826/8396622/83ead900-1dae-11e5-9686-a8ae867ccb0a.png)

**Comment by logsol** [comment]
![untitled](https://cloud.githubusercontent.com/assets/692826/8396624/9670e48e-1dae-11e5-9f6c-b87509c16db3.png)

**Comment by logsol** [comment]
![jucelibpd](https://cloud.githubusercontent.com/assets/692826/9131089/dab3a2ae-3ce8-11e5-8f0f-dd944afea9e9.jpg)

<img width="418" alt="screen shot 2015-08-07 at 09 45 22" src="https://cloud.githubusercontent.com/assets/692826/9131118/17ce75ba-3ce9-11e5-9419-1867a28902fc.png">

**Comment by o-g-sus** [comment]
![a7507d88-cf7d-11e5-8c66-68ae366ce378 1](https://cloud.githubusercontent.com/assets/692826/13394162/d47d87d8-dee6-11e5-81ed-616f92dc37a0.png)

**Comment by logsol** [comment]
![a7507d88-cf7d-11e5-8c66-68ae366ce378](https://cloud.githubusercontent.com/assets/692826/13393989/486e6d6c-dee5-11e5-85fc-7ff345ea6503.png)

**Comment by logsol** [comment]
<img width="19" alt="screen shot 2016-02-29 at 12 39 21" src="https://cloud.githubusercontent.com/assets/692826/13393480/038200d6-dee2-11e5-9db7-28aefeb7bc66.png">

**Comment by logsol** [comment]
<img width="54" alt="screen shot 2016-02-29 at 12 58 01" src="https://cloud.githubusercontent.com/assets/692826/13393827/2562091a-dee4-11e5-9f6e-1a338d527c8b.png">
